apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo-master
  namespace: default
spec:
  selector:
    matchLabels:
      app: jenkins-demo-master
  template:
    metadata:
      labels:
        app: jenkins-demo-master
    spec:
      containers:
      - image: anfeng/jenkins-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: jenkins-demo-master
        env:
        - name: branch
          value: <BRANCH_NAME>
